# Generated by Django 2.2 on 2020-11-04 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='行政区域的名字')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Areas')),
            ],
            options={
                'verbose_name': '行政区域',
                'verbose_name_plural': '行政区域',
                'db_table': 'areas',
            },
        ),
    ]
