# Generated by Django 2.2 on 2020-11-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default=None, max_length=200, verbose_name='住址'),
        ),
    ]
