# Generated by Django 2.2 on 2020-11-06 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_user_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='address',
        ),
    ]
